// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: user.proto

package userService

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *GetByIDRequest) Validate() error {
	return nil
}
func (this *GetByIDResponse) Validate() error {
	return nil
}
func (this *CreateRequest) Validate() error {
	return nil
}
func (this *CreateResponse) Validate() error {
	return nil
}
func (this *DeleteRequest) Validate() error {
	return nil
}
func (this *DeleteResponse) Validate() error {
	return nil
}
